version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: avalog_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: avalog
      POSTGRES_PASSWORD: avalog
      POSTGRES_DB: avalog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U avalog"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    image: avalog/api:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: avalog_api
    restart: always
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
